// <auto-generated />
using System;
using Avenga.EntityFramework.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avenga.EntityFramework.Migrations
{
    [DbContext(typeof(AcademyDbContext))]
    [Migration("20250702172643_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avenga.EntityFramework.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfClasses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# Basic",
                            NumberOfClasses = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "C# Advanced",
                            NumberOfClasses = 15
                        });
                });

            modelBuilder.Entity("Avenga.EntityFramework.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveCourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveCourseId = 1,
                            DateOfBirth = new DateTime(2002, 7, 2, 19, 26, 41, 936, DateTimeKind.Local).AddTicks(746),
                            FirstName = "Bob",
                            LastName = "Bobsky"
                        },
                        new
                        {
                            Id = 2,
                            ActiveCourseId = 2,
                            DateOfBirth = new DateTime(1997, 7, 2, 19, 26, 41, 936, DateTimeKind.Local).AddTicks(798),
                            FirstName = "Jill",
                            LastName = "Wayne"
                        },
                        new
                        {
                            Id = 3,
                            ActiveCourseId = 1,
                            DateOfBirth = new DateTime(2007, 7, 2, 19, 26, 41, 936, DateTimeKind.Local).AddTicks(802),
                            FirstName = "John",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("Avenga.EntityFramework.Models.Entities.Student", b =>
                {
                    b.HasOne("Avenga.EntityFramework.Models.Entities.Course", "ActiveCourse")
                        .WithMany("Students")
                        .HasForeignKey("ActiveCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveCourse");
                });

            modelBuilder.Entity("Avenga.EntityFramework.Models.Entities.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
